# Generated by Django 4.2.2 on 2024-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('pred_tex_code', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_annotated', models.BooleanField(default=False)),
                ('image_path', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
